spring.application.name=gymtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_tracker
spring.datasource.username=SPRING_DATASOURCE_USERNAME
spring.datasource.password=SPRING_DATASOURCE_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=JWT_SECRET_KEY
jwt.expiration-time=86400000